CREATE FUNCTION dbo.foo ()
RETURNS VARCHAR(100)
AS
BEGIN
    RETURN SUBSTRING(USER_NAME(), CHARINDEX('\', USER_NAME(), 1)+1, 30)
END
GO

CREATE FUNCTION dbo.bar(@dummy INT)
RETURNS DECIMAL(18, 8)
AS
BEGIN
    DECLARE @Result DECIMAL(18, 8);
    RETURN @Result
END
GO

CREATE FUNCTION dbo.zar(@dummy INT)
RETURNS CHAR(1)
AS
EXTERNAL NAME far.jar.tar;
GO
