CREATE PROC dbo.foo
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    DECLARE @var XML -- 1
END
GO

CREATE TRIGGER dbo.tr_foo ON dbo.bar
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AFTER DELETE
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    SELECT CAST('a' AS TIMESTAMP) -- 2
END
GO

CREATE FUNCTION dbo.foo (@code GEOGRAPHY) -- 3
RETURNS TABLE
WITH NATIVE_COMPILATION, SCHEMABINDING
AS
    RETURN

    SELECT id
    FROM dbo.bar
    WHERE code = @code
GO
