using Microsoft.SqlServer.TransactSql.ScriptDom;
using TeamTools.Common.Linting;
using TeamTools.TSQL.Linter.Routines;

namespace TeamTools.TSQL.Linter.Rules
{
    [RuleIdentity("SI0845", "MULTIPLE_OR_TO_IN")]
    internal sealed class MultipleOrToInRule : AbstractRule
    {
        private readonly CombinablePredicateExtractor predicateExtractor = new CombinablePredicateExtractor(false);

        public MultipleOrToInRule() : base()
        {
        }

        // A constraint and computed column definition must not use IN expression
        // unless DacFx fixes permanent diff generated by it.
        // See ConstraintWithoutListsRule
        public override void ExplicitVisit(CheckConstraintDefinition node)
        { }

        public override void ExplicitVisit(ColumnDefinition node)
        { }

        // Explicit - to avoid double visiting parts of complex AND-OR-AND-OR expression.
        public override void ExplicitVisit(BooleanBinaryExpression node)
        {
            if (node.BinaryExpressionType != BooleanBinaryExpressionType.Or)
            {
                // Forwarding to base visitor so the nested binary expressions will be processed
                Visit(node);

                // Only OR is supported by the rule
                return;
            }

            predicateExtractor.Process(node, ViolationHandlerWithMessage);
        }
    }
}
