SELECT 1 WHERE EXISTS(SELECT 0 FROM dbo.bar)

SELECT 1 WHERE EXISTS(SELECT (SELECT 0/0) FROM dbo.bar)

SELECT 1 WHERE EXISTS(SELECT '1' FROM dbo.bar)

SELECT 1 WHERE EXISTS(SELECT CASE WHEN @a = @b THEN 1 ELSE 0 END FROM dbo.bar)
