CREATE TABLE foo.bar
(
    sys_name        VARCHAR(20)  NOT NULL
    , profile_id    SMALLINT     NOT NULL
    , sign_datetime DATETIME2(0) NOT NULL
    , CONSTRAINT PK_foo_bar PRIMARY KEY NONCLUSTERED HASH (sys_name) WITH (BUCKET_COUNT = 8000000)
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);
GO
ALTER TABLE dbo.asdf ADD INDEX ix NONCLUSTERED HASH (id ASC, date DESC)
GO

CREATE TABLE jar.far
(
    rec_id              INT            NOT NULL
    , CONSTRAINT PK_jar_far PRIMARY KEY CLUSTERED  (rec_id) WITH (BUCKET_COUNT = 10000000)
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_ONLY);
GO
