CREATE PROC dbo.foo
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
FOR REPLICATION -- here
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    RETURN 1
END
GO

CREATE TRIGGER dbo.tr_foo ON dbo.bar
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
INSTEAD OF INSERT, UPDATE, DELETE
NOT FOR REPLICATION -- here
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    RETURN 1
END
GO
