CREATE PROC dbo.foo
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')

    PRINT '1';

    GOTO two;

    RAISERROR('3', 16, 1);
END
GO

CREATE TRIGGER dbo.tr_foo ON dbo.bar
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AFTER DELETE
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')

    PRINT '4';

    GOTO five;

    RAISERROR('6', 16, 1);
END
