CREATE TABLE dbo.foo
(
    some_data VARBINARY(100) ENCRYPTED WITH (COLUMN_ENCRYPTION_KEY = MyKey, ENCRYPTION_TYPE = RANDOMIZED, ALGORITHM = 'AEAD_AES_256_CBC_HMAC_SHA_256') NOT NULL
)
GO

DECLARE @handle UNIQUEIDENTIFIER

BEGIN DIALOG CONVERSATION @handle
FROM SERVICE src
TO SERVICE 'dst'
ON CONTRACT ctr
WITH lifetime = 86400, ENCRYPTION = ON
