CREATE TABLE dbo.foo
(
    some_data VARBINARY(100)
)
GO

DECLARE @handle UNIQUEIDENTIFIER

BEGIN DIALOG CONVERSATION @handle
FROM SERVICE src
TO SERVICE 'dst'
ON CONTRACT ctr
WITH lifetime = 86400

BEGIN DIALOG CONVERSATION @handle
FROM SERVICE src
TO SERVICE 'dst'
ON CONTRACT ctr
WITH lifetime = 86400, ENCRYPTION = OFF
