//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTools.Common.Linting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamTools.Common.Linting.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done linting files by plugins:.
        /// </summary>
        internal static string PluginMsg_DoneLintingByPlugins {
            get {
                return ResourceManager.GetString("PluginMsg_DoneLintingByPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0} - {1} files.
        /// </summary>
        internal static string PluginMsg_FilesLintedPerPlugin {
            get {
                return ResourceManager.GetString("PluginMsg_FilesLintedPerPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linting....
        /// </summary>
        internal static string PluginMsg_LintingBegins {
            get {
                return ResourceManager.GetString("PluginMsg_LintingBegins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded plugin: &apos;{0}&apos;, Version: &apos;{1}&apos;, Rules: {2}.
        /// </summary>
        internal static string PluginMsg_LoadedPluginInfo {
            get {
                return ResourceManager.GetString("PluginMsg_LoadedPluginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     for files: {0}.
        /// </summary>
        internal static string PluginMsg_LoadedPluginSupportedFiles {
            get {
                return ResourceManager.GetString("PluginMsg_LoadedPluginSupportedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0} plugin....
        /// </summary>
        internal static string PluginMsg_LoadingPlugin {
            get {
                return ResourceManager.GetString("PluginMsg_LoadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already loaded plugin &apos;{0}&apos;.
        /// </summary>
        internal static string PluginMsg_PluginAlreadyLoaded {
            get {
                return ResourceManager.GetString("PluginMsg_PluginAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starting with file: {0}.
        /// </summary>
        internal static string PluginMsg_StartingWithFile {
            get {
                return ResourceManager.GetString("PluginMsg_StartingWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     out of total {0} files..
        /// </summary>
        internal static string PluginMsg_TotalFilesLinted {
            get {
                return ResourceManager.GetString("PluginMsg_TotalFilesLinted", resourceCulture);
            }
        }
    }
}
