CREATE PROCEDURE dbo.test
    @id INT OUTPUT
AS
BEGIN
    SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

    BEGIN TRANSACTION;

    SAVE TRANSACTION dummy;

    EXEC dbo.foo
        @id = @id OUTPUT;

    IF XACT_STATE() = 1
        COMMIT TRANSACTION
    ELSE
        ROLLBACK TRANSACTION
END
GO
DROP PROCEDURE dbo.test
