CREATE MESSAGE TYPE foo
AUTHORIZATION dbo VALIDATION = NONE;
GO

CREATE CONTRACT bar
AUTHORIZATION dbo
(
    foo SENT BY TARGET
    , foo SENT BY INITIATOR
    , [http://schemas.microsoft.com/SQL/ServiceBroker/EndDialog] SENT BY ANY
);
GO

CREATE QUEUE jar
WITH ACTIVATION (STATUS = ON, PROCEDURE_NAME = dbo.handler, MAX_QUEUE_READERS = 10, EXECUTE AS N'dbo');
GO

CREATE SERVICE far
AUTHORIZATION dbo ON QUEUE jar(bar);
GO
