CREATE PROCEDURE dbo.test
    @param1   INT NOT NULL
    , @param2 BIT
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    SELECT 1 AS id;

    RETURN 0;
END;
GO

CREATE FUNCTION dbo.test3 (@param1 INT NOT NULL, @param2 BIT)
RETURNS TABLE
AS
    RETURN SELECT 1 AS id FROM dbo.my_table;
GO
