CREATE PROC dbo.foo
-- no params
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    RETURN 1
END
GO

CREATE PROC dbo.foo
    @bar INT NOT NULL,
    @far CHAR(1) NULL,
    @jar dbo.tbl READONLY -- this is fine
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    RETURN 1
END
