CREATE PROC dbo.foo
    @bar INT = NULL,    -- 1
    @far CHAR(1)        -- 2
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    RETURN 1
END
