SELECT 1, CONVERT(DATE, GETDATE())
UNION
SELECT NEWID(), CAST(GETDATE() AS TIME) -- 1, 2

GO

SELECT 1, CONVERT(DATE, GETDATE())
INTERSECT
SELECT NEWID(), CAST(GETDATE() AS TIME) -- 3, 4
GO

SELECT 1, CONVERT(DATE, GETDATE())
EXCEPT
SELECT NEWID(), CAST(GETDATE() AS TIME) -- 5, 6
GO
