DECLARE @foo TABLE 
(
    dt1 DATETIME  NOT NULL DEFAULT GETDATE(),
    dt2 DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    dt3 DATETIME  NULL,
    dt4 DATETIME2 NULL,
    dt5 AS GETDATE()
)

CREATE TABLE bar
(
    dt1 DATETIME  NOT NULL DEFAULT GETDATE(),
    dt2 DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    dt3 DATETIME  NULL,
    dt4 DATETIME2 NULL,
    dt5 AS GETDATE()
)
