//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTools.TSQL.ExpressionEvaluator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamTools.TSQL.ExpressionEvaluator.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is 0 here.
        /// </summary>
        internal static string ViolationDetails_DivideByZeroViolation_SourceIsZero {
            get {
                return ResourceManager.GetString("ViolationDetails_DivideByZeroViolation_SourceIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division by zero.
        /// </summary>
        internal static string ViolationDetails_IntentionalException_DivisionByZero {
            get {
                return ResourceManager.GetString("ViolationDetails_IntentionalException_DivisionByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0}&apos; has invalid value for {1} {2}.
        /// </summary>
        internal static string ViolationDetails_InvalidArgumentViolation_BadValue {
            get {
                return ResourceManager.GetString("ViolationDetails_InvalidArgumentViolation_BadValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expects {1} but {2} provided.
        /// </summary>
        internal static string ViolationDetails_InvalidNumberOfArgumentsViolation_CountMismatch {
            get {
                return ResourceManager.GetString("ViolationDetails_InvalidNumberOfArgumentsViolation_CountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} expects {1}-{2} but {3} provided.
        /// </summary>
        internal static string ViolationDetails_InvalidNumberOfArgumentsViolation_CountOutOfRange {
            get {
                return ResourceManager.GetString("ViolationDetails_InvalidNumberOfArgumentsViolation_CountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to source value is of type {0} and may contain Unicode symbol.
        /// </summary>
        internal static string ViolationDetails_NationalSymbolLoss_SourceMayContainUnicode {
            get {
                return ResourceManager.GetString("ViolationDetails_NationalSymbolLoss_SourceMayContainUnicode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is NULL here.
        /// </summary>
        internal static string ViolationDetails_NullArithmeticsViolation_SourceIsNull {
            get {
                return ResourceManager.GetString("ViolationDetails_NullArithmeticsViolation_SourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on numeric expression.
        /// </summary>
        internal static string ViolationDetails_NumbersHaveNoUnicode_ExpressionIsNumber {
            get {
                return ResourceManager.GetString("ViolationDetails_NumbersHaveNoUnicode_ExpressionIsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on &apos;{1}&apos;.
        /// </summary>
        internal static string ViolationDetails_NumbersHaveNoUnicode_LiteralValueIsNumber {
            get {
                return ResourceManager.GetString("ViolationDetails_NumbersHaveNoUnicode_LiteralValueIsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on {1} which is a number.
        /// </summary>
        internal static string ViolationDetails_NumbersHaveNoUnicode_VarIsNumber {
            get {
                return ResourceManager.GetString("ViolationDetails_NumbersHaveNoUnicode_VarIsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is out of range for {1}.
        /// </summary>
        internal static string ViolationDetails_OutOfRangeViolation_ValueIsOutOfTypeRange {
            get {
                return ResourceManager.GetString("ViolationDetails_OutOfRangeViolation_ValueIsOutOfTypeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}. Argument can be omitted.
        /// </summary>
        internal static string ViolationDetails_RedundantFunctionArgumentViolation_OmitArg {
            get {
                return ResourceManager.GetString("ViolationDetails_RedundantFunctionArgumentViolation_OmitArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already of type {1}.
        /// </summary>
        internal static string ViolationDetails_RedundantTypeConversionViolation_ValueIsAlreadyOfThisType {
            get {
                return ResourceManager.GetString("ViolationDetails_RedundantTypeConversionViolation_ValueIsAlreadyOfThisType", resourceCulture);
            }
        }
    }
}
