-- compatibility level min: 130
CREATE CLUSTERED COLUMNSTORE INDEX IX_FOO
ON dbo.BAR
WITH (DATA_COMPRESSION = COLUMNSTORE_ARCHIVE ON PARTITIONS (377), DATA_COMPRESSION = COLUMNSTORE_ARCHIVE ON PARTITIONS (378))
ON f(r);
