-- compatibility level min: 130
CREATE CLUSTERED COLUMNSTORE INDEX IX_FOO
ON dbo.BAR
WITH (DATA_COMPRESSION = COLUMNSTORE_ARCHIVE)
ON f(r);

CREATE CLUSTERED COLUMNSTORE INDEX IX_DOO
ON dbo.ZAR
WITH (DATA_COMPRESSION = COLUMNSTORE);

-- inline index
CREATE TABLE dbo.my_table
(
    id int not null
    , INDEX ix (id)  WITH (DATA_COMPRESSION = PAGE)
)
