-- compatibility level min: 130
CREATE TABLE dbo.my_table
(
    id int not null primary key clustered WITH (DATA_COMPRESSION = PAGE ON PARTITIONS (1), DATA_COMPRESSION = PAGE ON PARTITIONS (2), DATA_COMPRESSION = PAGE ON PARTITIONS (3))
    , INDEX ix (id)  WITH (DATA_COMPRESSION = PAGE ON PARTITIONS (1))
)
WITH (DATA_COMPRESSION = PAGE ON PARTITIONS (1), DATA_COMPRESSION = PAGE ON PARTITIONS (2), DATA_COMPRESSION = PAGE ON PARTITIONS (3));
