DECLARE @str VARCHAR(10);

SELECT 1
WHERE 1=1 AND (1=0 OR
    LOWER() IS NULL OR
    UPPER() IS NULL OR
    LTRIM() IS NULL OR
    RTRIM() IS NULL OR
    LEFT(@str) IS NULL OR
    RIGHT(@str) IS NULL OR
    ISJSON() IS NULL OR
    REPLACE(@str, 'asdf') IS NULL OR
    ISNULL(@str) IS NULL OR
    --NULLIF(@str) IS NULL OR
    DATEADD(dd, '1990101') IS NULL OR
    DATEDIFF(dd, '1990101') IS NULL OR
    DATENAME(GETDATE()) IS NULL OR
    DATEFROMPARTS(2000, 10) IS NULL OR
    YEAR() IS NULL OR
    DAY() IS NULL OR
    MONTH() IS NULL OR
    SIGN() IS NULL OR
    COUNT() IS NULL OR
    AVG() IS NULL OR
    SUM() IS NULL)
