ALTER TABLE dbo.foo ADD bar INT

ALTER TABLE dbo.foo ADD far BIT

ALTER TABLE dbo.foo ADD jar VARCHAR;
GO

ALTER TABLE dbo.foo DROP CONSTRAINT zar
ALTER TABLE dbo.foo DROP CONSTRAINT car
ALTER TABLE dbo.foo DROP CONSTRAINT tar
GO
