CREATE TABLE a
(
    b   INT     NOT NULL DEFAULT 1
    , c CHAR(1) NULL DEFAULT 'd'
    , bar AS CASE WHEN Id  = 1 OR Id = 2 OR Id = 3 THEN 10 ELSE 100 END
    , CONSTRAINT PK_a PRIMARY KEY (b)
);
GO

ALTER TABLE a ADD CONSTRAINT CHK CHECK (b > 0);
