SELECT 1
FROM dbo.foo
WHERE NOT EXISTS (SELECT COUNT(*) FROM dbo.bar)
GO

SELECT 1
FROM dbo.foo
WHERE EXISTS (SELECT COUNT(1) FROM dbo.bar)
GO

IF NOT EXISTS (SELECT COUNT(*) FROM dbo.bar)
    RETURN 1
GO

IF EXISTS (SELECT COUNT(1) FROM dbo.bar)
    RETURN 2
GO
