CREATE PROC dbo.foo
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    IF LEN('a') > 0
        SELECT TRY_CAST('asdf' AS NCHAR(10))

    RETURN 1
END
GO
