CREATE PROC dbo.foo
WITH NATIVE_COMPILATION, SCHEMABINDING, EXECUTE AS OWNER
AS
BEGIN ATOMIC WITH (TRANSACTION ISOLATION LEVEL = SNAPSHOT, LANGUAGE = N'English')
    IF XACT_STATE() <> 0 -- 1
        SELECT CHECKSUM( -- 2
            TRY_CONVERT(NCHAR(10), 'asdf')) -- 3

    RETURN 1
END
GO
