//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTools.TSQL.Linter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TeamTools.TSQL.Linter.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config already loaded.
        /// </summary>
        internal static string PluginMsg_ConfigAlreadyLoaded {
            get {
                return ResourceManager.GetString("PluginMsg_ConfigAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading config from.
        /// </summary>
        internal static string PluginMsg_FailedLoadingConfig {
            get {
                return ResourceManager.GetString("PluginMsg_FailedLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown compatibility level: {0}.
        /// </summary>
        internal static string PluginMsg_UnknownCompatibilityLevel {
            get {
                return ResourceManager.GetString("PluginMsg_UnknownCompatibilityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns {0} already included into {1}.
        /// </summary>
        internal static string ViolationDetails_AmbiguousUniquenessRule_ColumnAlreadyIncluded {
            get {
                return ResourceManager.GetString("ViolationDetails_AmbiguousUniquenessRule_ColumnAlreadyIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default is &apos;TABLE&apos;.
        /// </summary>
        internal static string ViolationDetails_BadLockEscalationForPartitionedTableRule_TableIsDefault {
            get {
                return ResourceManager.GetString("ViolationDetails_BadLockEscalationForPartitionedTableRule_TableIsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to estimated key size {0} is too big on {1} with {2} columns indexed.
        /// </summary>
        internal static string ViolationDetails_BloatedClusteredIndexRule_TooBig {
            get {
                return ResourceManager.GetString("ViolationDetails_BloatedClusteredIndexRule_TooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has {0} cols on {1}.
        /// </summary>
        internal static string ViolationDetails_BloatedClusteredIndexRule_TooManyCols {
            get {
                return ResourceManager.GetString("ViolationDetails_BloatedClusteredIndexRule_TooManyCols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing cursor &apos;{0}&apos; that was never used for fetching.
        /// </summary>
        internal static string ViolationDetails_CursorCommandOrderRule_ClosingNeverFetched {
            get {
                return ResourceManager.GetString("ViolationDetails_CursorCommandOrderRule_ClosingNeverFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deallocating unclosed &apos;{0}&apos; cursor.
        /// </summary>
        internal static string ViolationDetails_CursorCommandOrderRule_DeallocatingUnclosed {
            get {
                return ResourceManager.GetString("ViolationDetails_CursorCommandOrderRule_DeallocatingUnclosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching from not opened cursor &apos;{0}&apos;.
        /// </summary>
        internal static string ViolationDetails_CursorCommandOrderRule_FetchingFromNotOpened {
            get {
                return ResourceManager.GetString("ViolationDetails_CursorCommandOrderRule_FetchingFromNotOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor &apos;{0}&apos; was not deallocated.
        /// </summary>
        internal static string ViolationDetails_CursorCommandOrderRule_NotDeallocated {
            get {
                return ResourceManager.GetString("ViolationDetails_CursorCommandOrderRule_NotDeallocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening not declared or already opened cursor &apos;{0}&apos;.
        /// </summary>
        internal static string ViolationDetails_CursorCommandOrderRule_OpeningNotDeclared {
            get {
                return ResourceManager.GetString("ViolationDetails_CursorCommandOrderRule_OpeningNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redeclaring never deallocated cursor &apos;{0}&apos;.
        /// </summary>
        internal static string ViolationDetails_CursorCommandOrderRule_RedeclaringNotDeallocated {
            get {
                return ResourceManager.GetString("ViolationDetails_CursorCommandOrderRule_RedeclaringNotDeallocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use {0} instead.
        /// </summary>
        internal static string ViolationDetails_DeprecatedSystemViewRule_UseOtherOption {
            get {
                return ResourceManager.GetString("ViolationDetails_DeprecatedSystemViewRule_UseOtherOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see another occurance at line {0}.
        /// </summary>
        internal static string ViolationDetails_DuplicateConditionRule_SeeDupAtLine {
            get {
                return ResourceManager.GetString("ViolationDetails_DuplicateConditionRule_SeeDupAtLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is of type {1}.
        /// </summary>
        internal static string ViolationDetails_IdSuffixForIntegerTypesOnlyRule_ColIsOfType {
            get {
                return ResourceManager.GetString("ViolationDetails_IdSuffixForIntegerTypesOnlyRule_ColIsOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} on {0} type.
        /// </summary>
        internal static string ViolationDetails_InvalidTypeForNumericOperationRule_BadOp {
            get {
                return ResourceManager.GetString("ViolationDetails_InvalidTypeForNumericOperationRule_BadOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to size/precision is not a valid integer value.
        /// </summary>
        internal static string ViolationDetails_InvalidTypeSizeRule_NotInteger {
            get {
                return ResourceManager.GetString("ViolationDetails_InvalidTypeSizeRule_NotInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3} size {0} is out of range {1}-{2}.
        /// </summary>
        internal static string ViolationDetails_InvalidTypeSizeRule_OutOfRange {
            get {
                return ResourceManager.GetString("ViolationDetails_InvalidTypeSizeRule_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} at {1}.
        /// </summary>
        internal static string ViolationDetails_LiteralHasInvisibleCharRule_SymbolAtPos {
            get {
                return ResourceManager.GetString("ViolationDetails_LiteralHasInvisibleCharRule_SymbolAtPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATOMIC block expected.
        /// </summary>
        internal static string ViolationDetails_NativelyUnsupportedInstructionRule_AtomicBeginMissing {
            get {
                return ResourceManager.GetString("ViolationDetails_NativelyUnsupportedInstructionRule_AtomicBeginMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsupported isolation level {0}.
        /// </summary>
        internal static string ViolationDetails_NativelyUnsupportedInstructionRule_BadIsolationLevel {
            get {
                return ResourceManager.GetString("ViolationDetails_NativelyUnsupportedInstructionRule_BadIsolationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISOLATION LEVEL option required.
        /// </summary>
        internal static string ViolationDetails_NativelyUnsupportedInstructionRule_IsolationLevelMissing {
            get {
                return ResourceManager.GetString("ViolationDetails_NativelyUnsupportedInstructionRule_IsolationLevelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LANGUAGE option required.
        /// </summary>
        internal static string ViolationDetails_NativelyUnsupportedInstructionRule_LanguageMissing {
            get {
                return ResourceManager.GetString("ViolationDetails_NativelyUnsupportedInstructionRule_LanguageMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to numbered proc.
        /// </summary>
        internal static string ViolationDetails_NativelyUnsupportedInstructionRule_NumberedProc {
            get {
                return ResourceManager.GetString("ViolationDetails_NativelyUnsupportedInstructionRule_NumberedProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to temp proc.
        /// </summary>
        internal static string ViolationDetails_NativelyUnsupportedInstructionRule_TempProc {
            get {
                return ResourceManager.GetString("ViolationDetails_NativelyUnsupportedInstructionRule_TempProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string ViolationDetails_PartitionSchemeHardcoded_UseAllToPrimary {
            get {
                return ResourceManager.GetString("ViolationDetails_PartitionSchemeHardcoded_UseAllToPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETERROR - is of no use.
        /// </summary>
        internal static string ViolationDetails_RaisErrorOptionsRule_SetErrorIsOfNoUse {
            get {
                return ResourceManager.GetString("ViolationDetails_RaisErrorOptionsRule_SetErrorIsOfNoUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WITH LOG - stop spamming to the Server log.
        /// </summary>
        internal static string ViolationDetails_RaisErrorOptionsRule_WithLogSpam {
            get {
                return ResourceManager.GetString("ViolationDetails_RaisErrorOptionsRule_WithLogSpam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already granted.
        /// </summary>
        internal static string ViolationDetails_RedundantGrantRule_AlreadyGranted {
            get {
                return ResourceManager.GetString("ViolationDetails_RedundantGrantRule_AlreadyGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already given on schema {1}.
        /// </summary>
        internal static string ViolationDetails_RedundantGrantRule_AlreadyGrantedToSchema {
            get {
                return ResourceManager.GetString("ViolationDetails_RedundantGrantRule_AlreadyGrantedToSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use {0} instead.
        /// </summary>
        internal static string ViolationDetails_RedundantNegationRule_InsteadUse {
            get {
                return ResourceManager.GetString("ViolationDetails_RedundantNegationRule_InsteadUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to same seen at line {0}.
        /// </summary>
        internal static string ViolationDetails_RedundantNestedConditionRule_DupPos {
            get {
                return ResourceManager.GetString("ViolationDetails_RedundantNestedConditionRule_DupPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected {0} but was {1}.
        /// </summary>
        internal static string ViolationDetails_ReturnValueTypeMismatchRule_UnexpectedReturnValueType {
            get {
                return ResourceManager.GetString("ViolationDetails_ReturnValueTypeMismatchRule_UnexpectedReturnValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch to &apos;{0}&apos; and remove NOT.
        /// </summary>
        internal static string ViolationDetails_SimplePredicateNegationRule_UseReversedComparison {
            get {
                return ResourceManager.GetString("ViolationDetails_SimplePredicateNegationRule_UseReversedComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in {1}.
        /// </summary>
        internal static string ViolationDetails_SparseColumnIndexFilterRule_ColInIndex {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseColumnIndexFilterRule_ColInIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of total {1}.
        /// </summary>
        internal static string ViolationDetails_SparseColumnsAsSecondaryRule_CountOutOfTotal {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseColumnsAsSecondaryRule_CountOutOfTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be computed.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeComputed {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeComputed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be FILESTREAM.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeFilestream {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeFilestream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be IDENTITY.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeIdentity {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be NULLable.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeNotNullable {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be ROWGUIDCOL.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeRowguidCol {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_ColCannotBeRowguidCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot have DEFAULT.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_ColCannotHaveDefault {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_ColCannotHaveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table {0} cannot be compressed.
        /// </summary>
        internal static string ViolationDetails_SparseUnsupportedFeatureRule_TableCannotBeCompressed {
            get {
                return ResourceManager.GetString("ViolationDetails_SparseUnsupportedFeatureRule_TableCannotBeCompressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to param count {1}!={0}.
        /// </summary>
        internal static string ViolationDetails_SpExecuteParamDefinitionMatchRule_ParamCountMismatch {
            get {
                return ResourceManager.GetString("ViolationDetails_SpExecuteParamDefinitionMatchRule_ParamCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is {1}.
        /// </summary>
        internal static string ViolationDetails_TableKeyValidation_ColHasBadType {
            get {
                return ResourceManager.GetString("ViolationDetails_TableKeyValidation_ColHasBadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected hungarian prefix.
        /// </summary>
        internal static string ViolationDetails_TriggerNamePatternRule_HungarianPrefix {
            get {
                return ResourceManager.GetString("ViolationDetails_TriggerNamePatternRule_HungarianPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix is longer {0}.
        /// </summary>
        internal static string ViolationDetails_TriggerNamePatternRule_LongSuffix {
            get {
                return ResourceManager.GetString("ViolationDetails_TriggerNamePatternRule_LongSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unexpected schema prefix.
        /// </summary>
        internal static string ViolationDetails_TriggerNamePatternRule_SchemaPrefix {
            get {
                return ResourceManager.GetString("ViolationDetails_TriggerNamePatternRule_SchemaPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suffix is shorter {0}.
        /// </summary>
        internal static string ViolationDetails_TriggerNamePatternRule_ShortSuffix {
            get {
                return ResourceManager.GetString("ViolationDetails_TriggerNamePatternRule_ShortSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to missing table name prefix.
        /// </summary>
        internal static string ViolationDetails_TriggerNamePatternRule_TablePrefix {
            get {
                return ResourceManager.GetString("ViolationDetails_TriggerNamePatternRule_TablePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expected {0} but was {1}.
        /// </summary>
        internal static string ViolationDetails_TypeSynonymRule_ExpectedAnother {
            get {
                return ResourceManager.GetString("ViolationDetails_TypeSynonymRule_ExpectedAnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} of type {1} is not good enough for {2}.
        /// </summary>
        internal static string ViolationDetails_VariableTypePrecisionLackRule_TypeIsNoGood {
            get {
                return ResourceManager.GetString("ViolationDetails_VariableTypePrecisionLackRule_TypeIsNoGood", resourceCulture);
            }
        }
    }
}
