CREATE TABLE foo.bar
(
    sys_name        VARCHAR(20)  NOT NULL
    , sign_datetime DATETIME2(0) NOT NULL
    , CONSTRAINT PK_foo_bar PRIMARY KEY NONCLUSTERED HASH (sys_name) WITH (BUCKET_COUNT = 8000000)
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA, DATA_COMPRESSION = PAGE); -- compression
GO

CREATE TABLE foo.bar
(
    sys_name        VARCHAR(20)  NOT NULL
    , sign_datetime DATETIME2(0) NOT NULL
    , CONSTRAINT PK_foo_bar PRIMARY KEY NONCLUSTERED HASH (sys_name) WITH (BUCKET_COUNT = 8000000)
)
ON [PRIMARY] -- fg
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);
GO
