CREATE TABLE foo.bar
(
    sys_name        UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL -- 1
    , sign_datetime DATETIME2(0) SPARSE NULL -- 2
    , CONSTRAINT PK_foo_bar PRIMARY KEY NONCLUSTERED HASH (sys_name) WITH (BUCKET_COUNT = 8000000)
)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);
GO


CREATE TYPE foo.bar AS TABLE
(
    sys_name UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL -- 3
)
WITH (MEMORY_OPTIMIZED = ON);
GO
